language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_install:
    - skip=0
    - PHP=$TRAVIS_PHP_VERSION
    - if [[ ! $PHP = hhvm* ]]; then INI_FILE=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; else INI_FILE=/etc/hhvm/php.ini; fi
    - if [[ ! $skip ]]; then echo memory_limit = -1 >> $INI_FILE; fi
    - if [[ ! $skip ]]; then echo session.gc_probability = 0 >> $INI_FILE; fi
    - if [[ ! $skip ]]; then echo opcache.enable_cli = 1 >> $INI_FILE; fi
    - if [[ ! $skip && $PHP = 5.* ]]; then echo extension = memcache.so >> $INI_FILE; fi
    - if [[ ! $skip && $PHP = 5.* ]]; then (echo yes | pecl install -f apcu-4.0.10 && echo apc.enable_cli = 1 >> $INI_FILE); fi
    - if [[ ! $skip && $PHP = 7.* ]]; then (echo yes | pecl install -f apcu-5.1.2 && echo apc.enable_cli = 1 >> $INI_FILE); fi
    - if [[ ! $skip && $PHP = 5.* ]]; then pecl install -f memcached-2.1.0; fi
    - if [[ ! $skip ]]; then composer self-update --stable; fi

#   - if [[ $TRAVIS_PHP_VERSION =~ 5.[56] ]]; then echo yes | pecl install apcu-4.0.10; fi;
#   - if [[ $TRAVIS_PHP_VERSION =~ 5.[56] ]]; then echo "extension = apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
#   - if [[ $TRAVIS_PHP_VERSION =~ 5.[56] ]]; then echo "apc.enabled = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
#   - if [[ $TRAVIS_PHP_VERSION =~ 5.[56] ]]; then echo "apc.enable_cli = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
#   - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi

install:
   - composer install

