language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_install:
   - PHP_INI=~/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
   - |
      if [[ $TRAVIS_PHP_VERSION =~ 5.[56] ]]; then
          echo yes | pecl install apcu-4.0.10;
      fi;
   - |
      if [[ $TRAVIS_PHP_VERSION =~ 7.[10] ]]; then
          echo yes | pecl install apcu-5.1.2;
          "extension = memcached.so" >> $PHP_INI;
          git clone --branch php7 https://github.com/php-memcached-dev/php-memcached.git;
          cd php-memcached/; phpize; ./configure; make; make install;
      fi;
   - |
      if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then
          # echo "extension = apcu.so" >> $PHP_INI;
          echo "apc.enabled = 1" >> $PHP_INI;
          echo "apc.enable_cli = 1" >> $PHP_INI;
          # "extension = memcached.so" >> $PHP_INI;
      fi;

   - |
      if [[ $TRAVIS_PHP_VERSION =~ 7.[1] ]]; then
          "extension = memcached.so" >> $PHP_INI;
      fi;

install:
   - composer install

services:
   - memcached
